using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Our.Umbraco.Ditto.Resolvers.Archetype")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("MLWD")]
[assembly: AssemblyProductAttribute("Our.Umbraco.Ditto.Resolvers.Archetype")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) MLWD 2015")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.0.3")]
[assembly: AssemblyFileVersionAttribute("1.0.3")]

